POST http://localhost:9090/api/v1/account
Content-Type: application/json
Accept: application/json

{
  "full_name": "Rahmatul Izzah Annisa",
  "email": "rahmatul_izzah_annisa@gmail.com",
  "phone_number": "111111111111",
  "username": "izzah",
  "password": "izzah1231231"
}

###
GET http://localhost:9090/api/v1/account
Accept: application/json


###
GET http://localhost:9090/api/v1/account/59589ee3-a37a-40de-92a2-73fe197f1ba8m
Accept: application/json

##
DELETE http://localhost:9090/api/v1/account/59589ee3-a37a-40de-92a2-73fe197f1ba8
Accept: application/json

###
PUT http://localhost:9090/api/v1/account/a7416702-8794-40a9-84a1-f0279a1e6908
Content-Type: application/json

{
  "full_name": "Rahmatul Izzah Annisa Update",
  "email": "rahmatul_izzah_annisa_update@gmail.com",
  "phone_number": "111111111111"
}